dist: precise
language: c python
sudo: required
compiler: gcc
python:
- '3.5'
- '2.7'
script:
 - make
 - python setup.py install --install-dir .
 - python test/test.py
 - python3 setup.py install --install-dir .
 - python3 test/test.py
 - source test/test_c.sh
