language: c python
sudo: required
compiler: gcc
python:
- '3.6'
- '2.7'
before_install:
- sudo apt-get install -qq valgrind
script:
- make
- |
  if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then
  sudo python3 setup.py install
  python3 test/test.py
  fi
- |
  if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then
  sudo python setup.py install
  python test/test.py
  fi
- source test/test_c.sh
- valgrind --error-exitcode=42 --leak-check=full source test/test_c.sh
