language: c python
sudo: required
compiler: gcc
python:
- '3.6'
- '2.7'
env:
- VALGRIND_TEST_ON=1
before_install:
- sudo apt-get install -qq valgrind
script:
- make
- echo $TRAVIS_PYTHON_VERSION
- |
  if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then
  sudo python3 setup.py install
  python3 test/test.py
  python3 test/test_oldindex.py
  fi
- |
  if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then
  sudo python setup.py install
  python test/test.py
  python test/test_oldindex.py
  fi
- source test/test_c.sh  # valgrind test is applied when VALGRIND_TEST_ON=1
- source test/test_c_oldindex.sh  # test for old index
