language: c python r
sudo: true
compiler: gcc
r:
 - 3.1.3
 - 3.2.5
 - 3.3.0
script: 
 - make
 - python setup.py install
 - python test/test.py
 - cd Rpairix && make && R CMD SHLIB rpairix.c index.o bgzf.o --preclean 
