matrix:
  include:
    - language: c
      sudo: required
      compiler: gcc
      env:
      - VALGRIND_TEST_ON=1
      before_install:
      - sudo apt-get install -qq valgrind
      script:
      - make
      - source test/test_c.sh  # valgrind test is applied when VALGRIND_TEST_ON=1
      - source test/test_c_oldindex.sh  # test for old index
    - language: python
      sudo: required
      python:
      - '2.7'
      - '3.6'
      script:
      - sudo python3 setup.py install
      - python3 test/test.py
      - python3 test/test_oldindex.py
